# Generated by Django 2.2.4 on 2019-08-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0003_auto_20190825_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
