# Generated by Django 2.2.4 on 2019-08-25 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0004_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
