# Generated by Django 2.2.4 on 2019-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='b78447663c27', max_length=100),
        ),
    ]
