# Generated by Django 2.2.4 on 2019-09-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0010_auto_20190902_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='6fd26f11185a', max_length=100),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theangrydev.User')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theangrydev.Tag')),
            ],
        ),
    ]
