# Generated by Django 2.2.5 on 2019-09-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0011_auto_20190902_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='fe504285303e', max_length=100),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theangrydev.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theangrydev.User')),
            ],
        ),
    ]
