# Generated by Django 2.2.5 on 2019-09-05 02:53

from django.db import migrations, models
import theangrydev.models


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0013_auto_20190905_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=theangrydev.models.User.random_username, max_length=100),
        ),
    ]
