# Generated by Django 3.0.6 on 2020-05-17 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
