# Generated by Django 3.0.6 on 2020-05-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0021_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
