# Generated by Django 3.0.6 on 2020-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0022_auto_20200523_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://api.adorable.io/avatars/40/e1f2c206-ceda-447c-a81c-0b164def.png', max_length=75),
        ),
    ]
