# Generated by Django 3.0.6 on 2020-06-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theangrydev', '0025_auto_20200606_0230'),
        ('theangrydev', '0026_auto_20200609_0637'),
    ]

    operations = [
    ]
